springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 8082
  servlet:
    context-path: /Rain86/UserLogin2/1.0.0

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: live
  datasource:
    url: jdbc:h2:mem:party_identity;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS party_identity
    username: root
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
    name: party_identity
    data: classpath*:data/party_identity.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  application:
    name: Party-Identity
  data:
    rest:
      base-path: /api=false
  messages:
    always-use-message-format: true
    basename: i18n.messages
    cache-duration: 5000s
    encoding: UTF-8
    fallback-to-system-locale: true
