springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 8082
  servlet:
    context-path: /customer-service

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:party_identity;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS party_identity
    driver-class-name: org.h2.Driver
    platform: h2
    name: party_identity
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api=false
  messages:
    always-use-message-format: true
    basename: i18n.messages
    cache-duration: 5000s
    encoding: UTF-8
    fallback-to-system-locale: true
