# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sh gradlew clean dependencies --refresh-dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run Assemble!
      - run: sh gradlew assemble

  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Create Test-Results Directory
          command: |
            mkdir ~/repo/test-results

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      # sh gradlew --help
      # -P, --project-prop                 Set project property for the build script (e.g. -Pmyprop=myvalue).
      # -D, --system-prop                  Set system property of the JVM (e.g. -Dmyprop=myvalue).
      - run:
          name: Inject Secrets Vault INTO App
          command: |
            sh gradlew test --debug --system-prop VAULT_TOKEN=${VAULT_TOKEN} --system-prop VAULT_ADDR=${VAULT_ADDR}

      - store_test_results:
          path: ~/repo/test-results

  code_quality:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $SONAR_LOGIN

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run tests!
      - run: sh gradlew --refresh-dependencies dependencies test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Code Quality Metrics (Sonarqube) >> Code Quality Metrics (Sonarqube)
      - run: sh gradlew sonarqube

workflows:
  version: 2
  main:
    jobs:
      - build:
          context:
            - Spring-Swagger
            - Security
          filters:
            branches:
              only:
                - master
      - test:
          context:
            - Spring-Swagger
            - Security
          requires:
            - build
      - code_quality:
          context:
            - Spring-Swagger
            - Security
          requires:
            - test