# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-java/ for more details
#
version: 2.1
jobs:
  vault:
    docker:
      - image: vault:latest
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      VAULT_TOKEN: 00000000-0000-0000-0000-000000000000
      VAULT_ADDR: http://127.0.0.1:8200

    steps:
      #        name: Spawn Vault Docker Instance
      - run: vault server --dev --dev-root-token-id=00000000-0000-0000-0000-000000000000 & sleep 5
      #          name: Sleep (Wait for the Vault Instance to become available)
      #      - run:

      #          name: Inject Secrets into the Vault
      - run: vault kv put secret/party-identity/dev admin.username=admin-user admin.password=Mut4nt-Squ@ serv.username=service-user serv.password=Imm0Rt4L~P@ss spring.datasource.username=dev-db spring.datasource.password=S3cret\*\*DB
      - run: vault kv put secret/party-identity/live admin.username=admin-live admin.password=Mut4nt-l1ve-Squ@ serv.username=service-live serv.password=Imm0Rt4L~L1v3~P@ss spring.datasource.username=dev-db spring.datasource.password=l1v3_S3cret\*\*DB
  #    - run:
  #        name: ENV-Variables into the Vault
  #        command: |
  #          export VAULT_TOKEN=${VAULT_TOKEN}
  #          export VAULT_ADDR=${VAULT_ADDR}

  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sh gradlew clean dependencies --refresh-dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run Assemble!
      - run: sh gradlew assemble

  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Installing basic packages
      - run: apk update && apk add bash curl git zip unzip vault
      - run: gradle dependencies --refresh-dependencies
      #          name: Sleep (Wait for the Vault Instance to become available)
      #        name: Spawn Vault Docker Instance
      - run: vault server --dev --dev-root-token-id=00000000-0000-0000-0000-000000000000 & sleep 5

      #          name: Inject Secrets into the Vault
      - run: vault kv put secret/party-identity/dev admin.username=admin-user admin.password=Mut4nt-Squ@ serv.username=service-user serv.password=Imm0Rt4L~P@ss spring.datasource.username=dev-db spring.datasource.password=S3cret\*\*DB
      - run: vault kv put secret/party-identity/live admin.username=admin-live admin.password=Mut4nt-l1ve-Squ@ serv.username=service-live serv.password=Imm0Rt4L~L1v3~P@ss spring.datasource.username=dev-db spring.datasource.password=l1v3_S3cret\*\*DB

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      # sh gradlew --help
      # -P, --project-prop                 Set project property for the build script (e.g. -Pmyprop=myvalue).
      # -D, --system-prop                  Set system property of the JVM (e.g. -Dmyprop=myvalue).
      - run: sh gradle test --debug --system-prop VAULT_TOKEN=${VAULT_TOKEN} --system-prop VAULT_ADDR=${VAULT_ADDR}
      - store_test_results:
          path: test-results

  code_quality:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $SONAR_LOGIN

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run tests!
      - run: sh gradlew --refresh-dependencies dependencies test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Code Quality Metrics (Sonarqube) >> Code Quality Metrics (Sonarqube)
      - run: sh gradlew sonarqube

workflows:
  version: 2
  main:
    jobs:
      - vault:
          context:
            - Spring-Swagger
            - Security
      - build:
          requires:
            - vault
          context:
            - Spring-Swagger
            - Security
          filters:
            branches:
              only:
                - master
      - test:
          context:
            - Spring-Swagger
            - Security
          requires:
            - vault
            - build
      - code_quality:
          context:
            - Spring-Swagger
            - Security
          requires:
            - vault
            - test